### ISSUE TITLE
dead lock when run install

### ISSUE THREAD

**Issue by hellomxr** [continuent/tungsten-replicator#21]
hello, when i use the tungsten-replicator to transfer from mysql to mysql,  it occurs a deadlock problem as follows:
2018-07-18T09:09:06+08:00 [
  "install",
  "alpha",
  "--start-and-report"
]
2018-07-18T09:09:06+08:00 DEBUG >> Found directory, no need to create: /tmp/tungsten
2018-07-18T09:09:06+08:00 NOTE  >> Log output being sent to /tmp/tungsten/tungsten-configure.log
2018-07-18T09:09:06+08:00 DEBUG >> Logging started to /tmp/tungsten/tungsten-configure.log
2018-07-18T09:09:06+08:00 DEBUG >> The command is set to InstallCommand
2018-07-18T09:09:06+08:00 DEBUG >> Execute `ps ax 2>/dev/null | grep configure.rb | grep -v firewall | grep -v grep | awk '{print $1}'`
2018-07-18T09:09:06+08:00 DEBUG >> RC: 0, Result: 116169, No STDERR
2018-07-18T09:09:06+08:00 #####################################################################
2018-07-18T09:09:06+08:00 # Tungsten Replicator Configuration Procedure
2018-07-18T09:09:06+08:00 #####################################################################
2018-07-18T09:09:06+08:00 NOTE  >> Data service(s) alpha updated in /opt/tungsten-replicator-5.2.1/deploy.cfg
2018-07-18T09:09:06+08:00 INFO  >> Configuration saved to /opt/tungsten-replicator-5.2.1/deploy.cfg
2018-07-18T09:09:07+08:00 DEBUG >> Search ifconfig for 192.100.51.87
2018-07-18T09:09:07+08:00 DEBUG >> Search ifconfig for 192.100.51.87
2018-07-18T09:09:07+08:00 DEBUG >> Execute `if [ -f /opt/continuent/tungsten/tools/tpm ]; then /opt/continuent/tungsten/tools/tpm query version; else echo ""; fi`
2018-07-18T09:09:07+08:00 DEBUG >> RC: 0, Result: , No STDERR
2018-07-18T09:09:07+08:00 DEBUG >> Execute `if [ -f /opt/tungsten-replicator-5.2.1/tools/tpm ]; then /opt/tungsten-replicator-5.2.1/tools/tpm query version; else echo ""; fi`
2018-07-18T09:09:07+08:00 ERROR >> Unable to find the Ruby openssl library
2018-07-18T09:09:07+08:00 ERROR >> Unable to find the Ruby openssl library
2018-07-18T09:09:07+08:00 ERROR >> deadlock; recursive locking
2018-07-18T09:09:07+08:00 DEBUG >> deadlock; recursive locking
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configurator.rb:1608:in `synchronize'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configurator.rb:1608:in `synchronize'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configurator.rb:1581:in `stop_alive_thread'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configurator.rb:740:in `write'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configurator.rb:822:in `error'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configurator.rb:1655:in `rescue in block in ssh_result'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configurator.rb:1652:in `block in ssh_result'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configurator.rb:1609:in `block in synchronize'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configurator.rb:1608:in `synchronize'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configurator.rb:1608:in `synchronize'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configurator.rb:1650:in `ssh_result'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configurator.rb:1813:in `ssh_result'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configure/modules/package_cluster.rb:1302:in `block (2 levels) in get_deployment_configuration'
/usr/local/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/usr/local/lib/ruby/2.5.0/timeout.rb:33:in `block in catch'
/usr/local/lib/ruby/2.5.0/timeout.rb:33:in `catch'
/usr/local/lib/ruby/2.5.0/timeout.rb:33:in `catch'
/usr/local/lib/ruby/2.5.0/timeout.rb:108:in `timeout'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configure/modules/package_cluster.rb:1301:in `block in get_deployment_configuration'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configure/modules/package_cluster.rb:1299:in `each'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configure/modules/package_cluster.rb:1299:in `get_deployment_configuration'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configure/configure_command.rb:1175:in `block (3 levels) in build_deployment_configurations'
2018-07-18T09:09:07+08:00 DEBUG >> Execute `if [ -f /opt/continuent/tungsten/tools/tpm ]; then /opt/continuent/tungsten/tools/tpm query version; else echo ""; fi`
2018-07-18T09:09:07+08:00 ERROR >> Unable to find the Ruby openssl library
2018-07-18T09:09:07+08:00 DEBUG >> RC: 0, Result: , No STDERR
2018-07-18T09:09:07+08:00 DEBUG >> Execute `if [ -f /opt/tungsten-replicator-5.2.1/tools/tpm ]; then /opt/tungsten-replicator-5.2.1/tools/tpm query version; else echo ""; fi`
2018-07-18T09:09:07+08:00 ERROR >> Unable to find the Ruby openssl library
2018-07-18T09:09:07+08:00 ERROR >> deadlock; recursive locking
2018-07-18T09:09:07+08:00 DEBUG >> deadlock; recursive locking
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configurator.rb:1608:in `synchronize'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configurator.rb:1608:in `synchronize'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configurator.rb:1581:in `stop_alive_thread'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configurator.rb:740:in `write'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configurator.rb:822:in `error'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configurator.rb:1655:in `rescue in block in ssh_result'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configurator.rb:1652:in `block in ssh_result'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configurator.rb:1609:in `block in synchronize'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configurator.rb:1608:in `synchronize'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configurator.rb:1608:in `synchronize'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configurator.rb:1650:in `ssh_result'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configurator.rb:1813:in `ssh_result'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configure/modules/package_cluster.rb:1302:in `block (2 levels) in get_deployment_configuration'
/usr/local/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/usr/local/lib/ruby/2.5.0/timeout.rb:33:in `block in catch'
/usr/local/lib/ruby/2.5.0/timeout.rb:33:in `catch'
/usr/local/lib/ruby/2.5.0/timeout.rb:33:in `catch'
/usr/local/lib/ruby/2.5.0/timeout.rb:108:in `timeout'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configure/modules/package_cluster.rb:1301:in `block in get_deployment_configuration'
/opt/tungsten-replicator-5.2.1/tools/ruby-tpm/configure/modules/package_cluster.rb:1299:in `each'

my command is as the following:
1./tools/tpm update alpha --info --datasource-type=mysql --master=192.100.51.87 --members=192.100.51.88 --enable-heterogenous-slave=true --topology=master-slave --install-directory=/app/tungsten --start-and-report
2./tools/tpm install alpha --start-and-report

**Comment by mccont** [comment]
The underlying issue here is that you do not have the Ruby ssl libraries installed, which means the code is waiting for an SSH result it is not going to get. The line: 

Unable to find the Ruby openssl library

Indicates that you need to install the required Ruby libraries. See https://docs.continuent.com/tungsten-replicator-5.2-oss/prerequisite-host.html#prerequisite-host-network
