### ISSUE TITLE
is it support mysql innodb cluster to mongodb?

### ISSUE THREAD

**Issue by supersujj** [continuent/tungsten-replicator#9]
hi:
i just build a service from mysql innodb cluster to mongodb,but when i start the service in source ,it make a mistake:

./trepctl status
```
Processing status command...
NAME                     VALUE
----                     -----
appliedLastEventId     : NONE
appliedLastSeqno       : -1
appliedLatency         : -1.0
autoRecoveryEnabled    : false
autoRecoveryTotal      : 0
channels               : -1
clusterName            : mysql2mongo
currentEventId         : NONE
currentTimeMillis      : 1505872006833
dataServerHost         : 172-16-9-63
extensions             : 
host                   : 172-16-9-63
latestEpochNumber      : -1
masterConnectUri       : thl://localhost:/
masterListenUri        : thl://172-16-9-63:2112/
maximumStoredSeqNo     : -1
minimumStoredSeqNo     : -1
offlineRequests        : NONE
pendingError           : Event extraction failed
pendingErrorCode       : NONE
pendingErrorEventId    : NONE
pendingErrorSeqno      : -1
pendingExceptionMessage: Unexpected failure while extracting event bin-log.000167 (570)
pipelineSource         : UNKNOWN
relativeLatency        : -1.0
resourcePrecedence     : 99
rmiPort                : 10000
role                   : master
seqnoType              : java.lang.Long
serviceName            : mysql2mongo
serviceType            : unknown
simpleServiceName      : mysql2mongo
siteName               : default
sourceId               : 172-16-9-63
state                  : OFFLINE:ERROR
timeInStateSeconds     : 25.745
timezone               : GMT
transitioningTo        : 
uptimeSeconds          : 29.124
useSSLConnection       : false
version                : Tungsten Replicator 5.0.1
Finished status command...
[tungsten@gz-sharding-172-16-9-63 bin]$ ./trepctl -service mysql2mongo online
[tungsten@gz-sharding-172-16-9-63 bin]$  ./trepctl status
Processing status command...
NAME                     VALUE
----                     -----
appliedLastEventId     : bin-log.000167:0000000000000404;11172
appliedLastSeqno       : 0
appliedLatency         : 0.0
autoRecoveryEnabled    : false
autoRecoveryTotal      : 0
channels               : 1
clusterName            : mysql2mongo
currentEventId         : bin-log.000167:0000000000001329
currentTimeMillis      : 1505872035704
dataServerHost         : 172-16-9-63
extensions             : 
host                   : 172-16-9-63
latestEpochNumber      : 0
masterConnectUri       : thl://localhost:/
masterListenUri        : thl://172-16-9-63:2112/
maximumStoredSeqNo     : 0
minimumStoredSeqNo     : 0
offlineRequests        : NONE
pendingError           : Event extraction failed
pendingErrorCode       : NONE
pendingErrorEventId    : NONE
pendingErrorSeqno      : -1
pendingExceptionMessage: Unexpected failure while extracting event bin-log.000167 (570)
pipelineSource         : jdbc:mysql:thin://172-16-9-63:4306/tungsten_mysql2mongo?noPrepStmtCache=true
relativeLatency        : 481.704
resourcePrecedence     : 99
rmiPort                : 10000
role                   : master
seqnoType              : java.lang.Long
serviceName            : mysql2mongo
serviceType            : local
simpleServiceName      : mysql2mongo
siteName               : default
sourceId               : 172-16-9-63
state                  : OFFLINE:ERROR
timeInStateSeconds     : 2.717
timezone               : GMT
transitioningTo        : OFFLINE:ERROR
uptimeSeconds          : 57.995
useSSLConnection       : false
version                : Tungsten Replicator 5.0.1
Finished status command...
```

after it i find the seqno -1 ,the error is:
```
./thl -service tungsten list -seqno -1
Fatal error: Replicator static properties does not exist or is invalid: /opt/continuent/tungsten/tungsten-replicator/conf/static-tungsten.properties
com.continuent.tungsten.common.jmx.ServerRuntimeException: Replicator static properties does not exist or is invalid: /opt/continuent/tungsten/tungsten-replicator/conf/static-tungsten.properties
        at com.continuent.tungsten.replicator.conf.ReplicatorRuntimeConf.<init>(ReplicatorRuntimeConf.java:69)
        at com.continuent.tungsten.replicator.conf.ReplicatorRuntimeConf.getConfiguration(ReplicatorRuntimeConf.java:93)
        at com.continuent.tungsten.replicator.thl.THLManagerCtrl.main(THLManagerCtrl.java:1064)
```

what is the problem?

**Comment by supersujj** [comment]
trepsvc.log is: 
ERROR RelayLogTask Relay log task failed due to exce
ption: Error packet received: errno=1236 sqlstate=HY000 error= slave with the same server_uuid/server_id 
as this slave has connected to the master; the first event 'bin-log.000167' at 4, the last event read fro
m '/data/mysql/binlog_data/bin-log.000167' at 963, the last byte read from '/data/mysql/binlog_data/bin-l
og.000167' at 963.
com.continuent.tungsten.replicator.extractor.ExtractorException: Error packet received: errno=1236 sqlsta
te=HY000 error= slave with the same server_uuid/server_id as this slave has connected to the master; the 
first event 'bin-log.000167' at 4, the last event read from '/data/mysql/binlog_data/bin-log.000167' at 9
63, the last byte read from '/data/mysql/binlog_data/bin-log.000167' at 963.
        at com.continuent.tungsten.replicator.extractor.mysql.RelayLogClient.processEvent(RelayLogClient.
java:515)
        at com.continuent.tungsten.replicator.extractor.mysql.RelayLogTask.run(RelayLogTask.java:58)
        at java.lang.Thread.run(Thread.java:748)

**Comment by mccont** [comment]
We don't support extraction from InnoDB cluster. We do from standard MySQL/InnoDB, but not the cluster product.
